### ISSUE TITLE
Not Working after day 1

### ISSUE THREAD

**Issue by kendrisms** [ryanries/ADReplStatus#23]
Installed and ran 2 days ago without issue.  Then tried to run next day and it shows 0% and then disappears and never counts up or starts.  Tried on different machines, rebooted, same thing.

**Comment by kendrisms** [comment]
It starts fine, shows 0% and then does not count up and finish, percentage disappears.
![Screenshot 2023-06-09 203049](https://github.com/ryanries/ADReplStatus/assets/136133644/07cc7873-ab08-445d-9771-7dbb0d567e68)
![2](https://github.com/ryanries/ADReplStatus/assets/136133644/5d19b6da-44cc-4bae-aedc-6039ea440e7f)

**Comment by NikVanT** [comment]
Can you enable logging and provide us the log file please?

**Comment by ildrososgr** [comment]
Same problem here log file contains only there : 
[16/06/2023 10:19:45] Logging enabled.
[16/06/2023 10:19:46] Attempting to connect to forest xxxxxx.local as currently logged-on user.
[16/06/2023 10:19:46] Found 6 domains in forest xxxxxx.local.

**Comment by glaucon1984** [comment]
> Same problem here log file contains only there : [16/06/2023 10:19:45] Logging enabled. [16/06/2023 10:19:46] Attempting to connect to forest xxxxxx.local as currently logged-on user. [16/06/2023 10:19:46] Found 6 domains in forest xxxxxx.local.

I have the exact same issue.

**Comment by ryanries** [comment]
@kendrisms @ildrososgr @glaucon1984 @NikVanT 

I haven't been able to repro here. I feel like this probably has something to do with not having line of sight to the DC or not having all the required ports open BUT if that is the case I would like to do a better job of logging the error.

Could one of you perhaps take a memory dump of the process using procdump -ma while the app is in state?  And by in-state, what I mean is, while the button is greyed out and it appears "hung" ?

Or a TTD (time travel debugging) trace would be even better.

You can send it to my personal email ryanries09@gmail.com

Thanks

**Comment by ryanries** [comment]
Or a TTD (time travel debugging) trace would be even better

**Comment by vandreytrindade** [comment]
Hi! I have the same problem. I have added a new DC yesterday, since then the tool is not showing my DC's anymore.

[04/08/2023 14:43:04] Logging enabled.
[04/08/2023 14:43:05] Attempting to connect to forest dagostini.local as currently logged-on user.
[04/08/2023 14:43:05] Found 1 domains in forest domain.local.

**Comment by vandreytrindade** [comment]
Hi, the problem has been solved. There is a problem on my environment, once I started solving it the tool started to show the replication is failing on one of the three DC's.
Thanks, great tool!

**Comment by ryanries** [comment]
@vandreytrindade Thanks... can you give me more details on what exactly you fixed in your environment? I figured this problem  had something to do with the AD environment, but I'd really like to know exactly what so I can replicate it myself and be able to report on it better in the tool so other people who have this issue know what's going on. Thanks!

**Comment by kendrism** [comment]
We continue to occasionally have this problem.  I have this problem today.  I am running from the PDC.  Logs have nothing in them.  We have a large environment.

**Comment by vandreytrindade** [comment]
> @vandreytrindade Thanks... can you give me more details on what exactly you fixed in your environment? I figured this problem had something to do with the AD environment, but I'd really like to know exactly what so I can replicate it myself and be able to report on it better in the tool so other people who have this issue know what's going on. Thanks!

Hey Ryan! Sorry for not reaching out sooner!
I still didn't fixed my environment, first time using three sites and still learning about it...
But the problem happened when the third DC was created and there was a firewall blocking everything (I still don't know how the first sync happened) and when I opened your tool to check for replication errors it wasn't reporting anything.
It only started to show an RPC error on the third DC after I solved the problem where the DC hasn't created the Netlogon, Sysvol shares.

**Comment by deanoporter** [comment]
Make sure you run it elevated, I've had little issues when I don't.

Great tool though, thanks :)

**Comment by toky76** [comment]
Hi,
the same problem with not showing anything.
The log says:
[3/5/2024 2:25:16 PM] Logging enabled.
[3/5/2024 2:25:17 PM] Attempting to connect to forest <mydomain> as currently logged-on user.
[3/5/2024 2:25:17 PM] Found 21 domains in forest lindt.net.

**Comment by vandreytrindade** [comment]
> Hi, the same problem with not showing anything. The log says: [3/5/2024 2:25:16 PM] Logging enabled. [3/5/2024 2:25:17 PM] Attempting to connect to forest as currently logged-on user. [3/5/2024 2:25:17 PM] Found 21 domains in forest lindt.net.

Hi @toky76 , in my case it was replications problems, now it shows everything correctly.

**Comment by vandreytrindade** [comment]
> > @vandreytrindade Thanks... can you give me more details on what exactly you fixed in your environment? I figured this problem had something to do with the AD environment, but I'd really like to know exactly what so I can replicate it myself and be able to report on it better in the tool so other people who have this issue know what's going on. Thanks!
> 
> Hey Ryan! Sorry for not reaching out sooner! I still didn't fixed my environment, first time using three sites and still learning about it... But the problem happened when the third DC was created and there was a firewall blocking everything (I still don't know how the first sync happened) and when I opened your tool to check for replication errors it wasn't reporting anything. It only started to show an RPC error on the third DC after I solved the problem where the DC hasn't created the Netlogon, Sysvol shares.

Update: Now that we have no replication problems, the tool shows replication correctly.

**Comment by bdrogja** [comment]
Will this tool be still maintained?
Tried it in an broken multi domain forest, same issue as anybody above.

If its not working because of health problems in an domain, its useless right?

**Comment by barbarajoost** [comment]
I know that the tool is able to show errors, f. e. when the replication topology is broken. But it shows only that there is an error, not why. The tool gives you a short overview over the replication status of the domain, but it depends on working backbone services like DNS and the DC locator process, I think. IMO the tool is not a replacement for classic monitoring tools like SCOM. I use the tool to check that the replication works again after the monthly updates and to see the replication topology in a simple manner. But for serious troubleshooting I have SCOM.

In the end this tool is a GUI for the command line tool repadmin. If you know already that your domain is broken, you should start with repadmin and checking the event logs of the DCs. I hope for you that you have SCOM or a log server like an ELK-stack for that. Otherwise, this can become painful because of the masses of events.
